### ISSUE TITLE
Only a few games are shown

### ISSUE THREAD

**Issue by DarkUnicycle** [ItsLogic/Xbox-Achievement-Unlocker#6]
When I open the program only about 9 games are shown out of my list of games that I've played.
On a side note, I just wanted to thank you for what you're doing. I created this account to help in any way I can and let you know you're awesome.

![Screenshot 2022-07-28 000546](https://user-images.githubusercontent.com/110148404/181417976-844d06b4-7014-4f7a-a8e6-6653ff0f5a3e.png)

**Comment by ItsLogic** [comment]
Well this is a new one I guess I didnt notice the error in my code from random chance because of the games I have played recently. It seems like a simple issue so it should be fixed by next release whenever I decide that is 
(Its only supposed to be two rows of 6 anyway so you are only missing three of your games)

**Comment by DarkUnicycle** [comment]
hay, after messing around with the program I was able to have it refresh the game list within the program to show a different set of 12. Not sure if this is intended but it's a nice feature. It only works a few times

**Comment by HaZheRMx** [comment]
click on grab info again (3 times xD) and solve the problem

**Comment by ItsLogic** [comment]
This should be fixed now. I both fixed the bug and increased the limit to 42 games
